# Generated by Django 4.2.3 on 2023-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("mL", "milliliter"),
                            ("L", "liter"),
                            ("dL", "deciliter"),
                            ("tsp.", "teaspoon"),
                            ("tbsp.", "tablespoon"),
                            ("fl oz", "fluid ounce"),
                            ("c", "cup"),
                            ("pt", "pint"),
                            ("qt", "quart"),
                            ("gal", "gallon"),
                            ("mg", "milligram"),
                            ("g", "gram"),
                            ("kg", "kilogram"),
                            ("lb", "pound"),
                            ("oz", "ounce"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price_per_unit", models.FloatField()),
                ("ap_weight", models.FloatField()),
                ("trim_weight", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("inventory_items", models.ManyToManyField(to="recipe.inventoryitem")),
            ],
        ),
    ]
